# Configuration fragment for anchoring of a wrist rest to the main body,
# demonstrating the use of multiple mounts with a consistent angle to allow
# the position of the wrist rest to be adjusted.

wrist-rest:
  include: true
  style: threaded
  mounts:
  - fasteners:
      bolt-properties:
        m-diameter: 4
        head-type: socket
        total-length: 60
      height:
        first: 3
    angle: -1.2
    blocks:
      distance: 35
      width: 10
      partner-side:
        anchoring:
          anchor: t4
          side: NNE
          segment: 3
          offset: [7, -9]
        depth: 10
      wrist-side:
        depth: 7
        pocket-height: -100
      aliases:
        wr0c: partner-side
        wr0p: wrist-side
  - fasteners:
      bolt-properties:
        m-diameter: 4
        head-type: socket
        total-length: 45
      height:
        first: 3
    angle: -1.2
    blocks:
      distance: 30
      width: 10
      partner-side:
        anchoring:
          anchor: near-right
          side: SSW
          segment: 3
          offset: [-5, 0]
        depth: 7
      wrist-side:
        depth: 7
        pocket-height: -100
      aliases:
        wr1c: partner-side
        wr1p: wrist-side
