# Configuration fragment for mutual anchoring.

wrist-rest:
  include: true
  style: threaded
  mounts:
  - fasteners:
      bolt-properties:
        m-diameter: 6
        head-type: socket
        total-length: 55
      heights: [7]
    authority: mutual
    blocks:
      width: 13
      partner-side:
        anchoring:
          anchor: t4
          side: NNE
          segment: 3
          extrinsic-offset: [7, -6, 0]
        depth: 10
      wrist-side:
        anchoring:
          anchor: plinth-left
          extrinsic-offset: [10, 4, 0]
        depth: 8
    aliases:
      blocks:
        wr0p: partner-side
        wr0w: wrist-side
      nuts:
        wr0p0: [partner-side, 0]
        wr0w0: [wrist-side, 0]
tweaks:
  wrist-rest-nut-pockets:
  - at-ground: true
    positive: false
    hull-around: [[wr0w0]]
