# A configuration fragment for a simple 12-key macropad.
# This might also serve as the core of a numpad and is easily extended.

key-clusters:
  main:
    anchoring:
      anchor: origin
      intrinsic-offset: [0, 0, 4.5]
    matrix-columns:
    - rows-above-home: 3
    - rows-above-home: 3
    - rows-above-home: 3
    aliases:
      back: [1, last]
      lower-left: [first, first]
      upper-left: [first, last]
      lower-right: [last, first]
      mid-right: [last, 2]
      upper-right: [last, last]
by-key:
  parameters:
    layout:
      pitch:
        intrinsic: -0.1
        base: 0.3
    wall:
      extent: 2
      to-ground: true
      parallel: 4
      perpendicular: -16
  clusters:
    main:
      columns:
        last:
          rows:
            last:
              sides:
                east:
                  parameters:
                    wall:
                      extent: 1
  sides:
    north:
      parameters:
        wall:
          parallel: 8
          perpendicular: -2
secondaries:
  back-wall:
    anchoring:
      anchor: upper-right
      side: NNE
      segment: 3
    translation: [0, 0, -10]
mcu:
  include: true
  anchoring:
    anchor: back-wall
    intrinsic-rotation: [0, π/2, π/-2]  # Stand on the long edge.
    intrinsic-offset: [0, -3.5, 0]
  support:
    lock:
      include: true
      plate:
        backing-thickness: 3
