# A configuration fragment for a simple 12-key macropad.
# This might also serve as the core of a numpad and is easily extended.

key-clusters:
  main:
    position:
      anchor: origin
      offset: [0, 0, 4.5]
    matrix-columns:
    - rows-above-home: 3
    - rows-above-home: 3
    - rows-above-home: 3
    aliases:
      lower-left: [first, first]
      upper-left: [first, last]
      lower-right: [last, first]
      upper-right: [last, last]
by-key:
  parameters:
    layout:
      pitch:
        intrinsic: -0.1
        base: 0.3
    wall:
      bevel: 1
      north:
        extent: 0
      east:
        parallel: 10
        perpendicular: -23
      south:
        parallel: 10
        perpendicular: -23
      west:
        parallel: 10
        perpendicular: -23
case:
  key-mount-thickness: 3
  web-thickness: 3
  rear-housing:
    include: true
    wall-thickness: 1.5
    roof-thickness: 1
    position:
      offsets:
        north: 11
        south: 2
    height: 24.5
mcu:
  include: true
  # Stand on the long edge folded into the rear housing.
  intrinsic-rotation: [0, 1.5708, -1.5708]
  position:
    anchor: rear-housing
    side: ENE
    segment: 2  # Midway up the wall.
    offset: [-1, -1.25, 0]
  support:
    lock:
      include: true
