# Configuration fragment for an open case.
# Key aliases used herein refer to dmote/base.yaml.

main-body:
  bottom-plate:
    include: false
  foot-plates:
    include: true
    height: 3
    polygons:
    - points:
      - anchor: rear-housing
        side: NNW
        offset: [0, 0]
      - anchor: rear-housing
        side: NNW
        offset: [10, 0]
      - anchor: rear-housing
        side: NNW
        offset: [0, -10]
    - points:
      - anchor: a1
        side: WNW
        offset: [7, 0]
      - anchor: a1
        side: NNE
      - anchor: a1
        side: ESE
        offset: [0, -6]
    - points:
      - anchor: near-right
        side: SSW
        offset: [4, 1]
      - anchor: near-right
        side: NNE
        offset: [1, -5]
      - anchor: near-right
        side: ESE
wrist-rest:
  bottom-plate:
    include: false
