# A configuration fragment for Tom Short’s Dactyl-ManuForm, ca. v0.4.

# The long-term goal with this file is to have it produce Short’s design
# through the DMOTE application for upstream compatibility.
# Similarity is checked by placing Short’s “right-4x5.stl” file
# in the things/scad/ folder and then injecting it into a DMOTE output:
#
# $ echo '%import("right-4x5.stl");' >> things/scad/right-hand-case-main.scad
#
# In that Linux-style shell command, $ represents your prompt.
#
# As of DMOTE v0.6.0, the application is still missing the wire hook
# feature on the original Dactyl-ManuForm, though it could be imitated
# with the tweaks feature. A vertex-perfect imitation would be laborious
# in any case.

keys:
  styles:
    default:  # Rough approximation of SA family.
      style: maquette
      switch-type: mx
      skirt-length: 5.75
      top-size: [12.7, 12.7, 6]
      unit-size: [1, 1]
    big:
      style: maquette
      switch-type: mx
      skirt-length: 5.75
      top-size: [12.7, 20, 6]
      unit-size: [1, 1.5]
key-clusters:
  main:
    anchoring:
      anchor: origin
      # To match upstream STL more exactly, raise by the thickness of the
      # bottom plate. The Dactyl-ManuForm was not raised above the ground
      # plane to compensate for a bottom plate, but the DMOTE is.
      offset: [1, 0, 12.9]
    matrix-columns:
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 1
    aliases:
      m00: [0, first]
      m01: [1, first]
      m02: [2, first]
      m03: [3, first]
      m04: [4, first]
      mcu-base-key: [0, 0]
      back0: [0, last]
      back1: [1, last]
      back2: [2, last]
      back3: [3, last]
      right0: [last, 0]
  thumb0:
    anchoring:
      anchor: m00
      offset: [-2, -28, -6]
    matrix-columns:
    - rows-above-home: 0
    - rows-above-home: 0
    aliases:
      thumb-tr: [1, 0]  # Top right.
      thumb-tl: [0, 0]
  thumb1:
    anchoring:
      anchor: thumb-tl
      offset: [3.5, -26, -15]
    matrix-columns:
    - rows-above-home: 1
    - rows-above-home: 1
    aliases:
      thumb-mr: [1, 0]
      thumb-ml: [1, 1]
      thumb-br: [0, 0]
      thumb-bl: [0, 1]
by-key:
  parameters:
    layout:
      matrix:
        separation:
          column: 1.5
          row: 1.2
    wall:
      parallel: 5
      perpendicular: -15
  clusters:
    main:
      parameters:
        layout:
          matrix:
            neutral:
              column: 3
          pitch:
            base: 0
            progressive: 0.25
          roll:
            base: 0.26
            progressive: 0.09
      columns:
        first:
          sides:
            west:
              parameters:
                wall:
                  extent: 2
                  to-ground: true
                  parallel: 8
                  perpendicular: -9
        "2":
          parameters:
            layout:
              translation:
                mid: [0, 2.82, -4.5]
        "3":
          sides:
            east:
              parameters:
                wall:
                  extent: 1
                  to-ground: false
            south:
              parameters:
                wall:
                  extent: 2
                  to-ground: true
        "4":
          parameters:
            layout:
              translation:
                late: [1, -12, 5.64]
            wall:
              extent: 2
              to-ground: true
      sides:
        north:
          parameters:
            wall:
              extent: 2
              to-ground: true
        east:
          parameters:
            wall:
              extent: 2
              to-ground: true
    thumb0:
      parameters:
        key-style: big
        layout:
          pitch:
            base: 0.1745
          roll:
            base: -0.4014
          yaw:
            base: 0.1745
      columns:
        first:
          parameters:
            layout:
              roll:
                intrinsic: 0
              yaw:
                intrinsic: 0
        last:
          parameters:
            layout:
              translation:
                late: [3, -4, -2.2]
    thumb1:
      parameters:
        layout:
          matrix:
            neutral:
              column: 1
            separation:
              column: 1
          pitch:
            base: -0.02
          roll:
            base: -0.59
          yaw:
            base: 0.94
        wall:
          extent: 2
          to-ground: true
      columns:
        first:
          parameters:
            wall:
              parallel: 2
              perpendicular: -6
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.26
                  translation:
                    early: [0, -1, 1.7]
            last:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.05
                  translation:
                    early: [0, 1, 5.2]
          sides:
            west:
              parameters:
                wall:
                  perpendicular: -4
        last:
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.1
                  yaw:
                    intrinsic: -0.06
                  translation:
                    early: [1.5, 0, 2.7]
            last:
              parameters:
                layout:
                  yaw:
                    intrinsic: -0.2
                  translation:
                    early: [0.6, 8, 4.5]
      sides:
        east:
          parameters:
            wall:
              extent: 0
              to-ground: false
secondaries:
  back-plane:
    anchoring:
      anchor: back0
      side: NNE
      segment: 3
    override: [null, null, 3]
main-body:
  reflect: true
  key-mount-thickness: 4
  key-mount-corner-margin: 1.5
  web-thickness: 3.5
  bottom-plate:
    include: true
    installation:
      dome-caps: true
      thickness: 1.2
      inserts:
        include: true
        diameter:
          top: 5.1
          bottom: 5.31
        length: 3.8
      fasteners:
        bolt-properties:
          m-diameter: 3  # Speculation; Short may have used non-metric.
          head-type: countersunk
          total-length: 6
          include-threading: false  # Threading not used with inserts.
        positions:
        - anchor: thumb-ml
          side: N
          segment: 3
          offset: [2, 0]
        - anchor: back0
          side: W
          segment: 3
          offset: [1, 0]
        - anchor: back3
          side: N
          segment: 3
          offset: [0, -2]
        - anchor: right0
          side: E
          segment: 3
          offset: [-2, 0]
        - anchor: m02
          side: S
          segment: 3
          offset: [-4, -6]
tweaks:
  webbing:
    - chunk-size: 3
      hull-around:  # Between the two thumb clusters.
      - [thumb-tl, WNW, 0]
      - [thumb-ml, ENE, 0]
      - [thumb-tl, WSW, 0]
      - [thumb-ml, ESE, 0]
      - [thumb-tl, SSE, 0]
      - [thumb-mr, ENE, 0]
      - [thumb-tr, SSW, 0]
      - [thumb-mr, SSE, 0]
      - [thumb-tr, SSE, 0]
    - chunk-size: 3
      hull-around:  # Between thumb0 and the main cluster.
      - [thumb-tl, NNW, 0]
      - [m00, SSW, 0]
      - [thumb-tl, NNE, 0]
      - [m00, SSE, 0]
      - [thumb-tr, NNW, 0, 1]
      - [m01, SSW, 0]
      - [thumb-tr, NNE, 0, 1]
      - hull-around:
        - [m01, SSE, 0]
        - [m02, WNW, 0]
      - [thumb-tr, ENE, 0, 1]
      - hull-around:
        - [m02, WNW, 0]
        - [m02, WSW, 0]
      - [thumb-tr, ESE, 0, 1]
      - [m02, SSW, 0]
      - hull-around:
        - [m02, SSE, 0]
        - [m03, WSW, 0]
  near-low-corner:
    - chunk-size: 2
      at-ground: true
      hull-around:
      - [m03, SSE, 2]
      - [m03, ESE, 2]
      - [m03, E, 2]
    - hull-around:
      - [m03, SSE, 1, 2]
      - [m03, ESE, 1, 2]
    - hull-around:
      - [m03, ESE, 1, 2]
      - [m03, E, 1, 2]
  to-floor:
    - at-ground: true
      hull-around:
      - [m00, WSW, 2, 3]
      - [thumb-ml, NNE, 2, 3]
    - at-ground: true
      hull-around:
      - [thumb-ml, NNW, 2, 3]
      - [thumb-bl, NNE, 2, 3]
    - at-ground: true
      hull-around:
      - [m03, SSW, 2, 3]
      - [thumb-tr, SSE, 2, 3]
    - at-ground: true
      hull-around:
      - [thumb-tr, SSE, 2, 3]
      - [thumb-mr, SSE, 2, 3]
    - at-ground: true
      hull-around:
      - [thumb-mr, SSW, 2, 3]
      - [thumb-br, SSE, 2, 3]
  bottom-plate-only:
    - at-ground: true
      above-ground: false
      hull-around:
      - [m03, E, 2]
      - [m03, ESE, 2]
      - [m03, SSE, 2]
      - [m03, SSW, 2]
    - at-ground: true
      above-ground: false
      hull-around:
      - [thumb-mr, SSE, 2]
      - [thumb-ml, NNE, 2]
      - [m00, WSW, 2]
      - [m03, NE]
      - [thumb-tr, SSE, 2]
  thumb-to-finger-gap:
    - chunk-size: 3
      hull-around:
      - [m00, WSW, 0, 1]
      - [m00, WSW, 2, 3]
      - [thumb-tl, WNW, 0]
      - [thumb-ml, NNE, 0, 3]
    - chunk-size: 2
      hull-around:
      - [thumb-mr, SSE, 0, 3]
      - [thumb-tr, SSE, 0, 3]
      - [m03, SSW, 0, 3]
  ports:
    # Holes from port holders into the case.
    - {positive: false,
       anchoring: {anchor: big-port, side: S, offset: [0, 0, 5]},
       size: [10.78, 13, 5]}
    - {positive: false,
       anchoring: {anchor: small-port},
       size: [6.5, 20, 13.6]}
mcu:
  include: true
  type: promicro
  intrinsic-rotation: [0, π/2, 0]
  anchoring:
    anchor: back-plane
    offset: [-17, -20, 11]
  support:
    shelf:
      include: true
      extra-space: [3, 19.9, 0.43]
      thickness: 3
      sides:
        lateral-thickness: 4
        overhang-thickness: 4
        overhang-width: 3
        offsets: [-34.9, 0]
ports:
  big-port:
    # This models an unknown variety of RJ9 socket.
    include: true
    type: custom
    size: [10.78, 9, 18.38]
    alignment:
      side: NE
      segment: 2
    anchoring:
      anchor: back-plane
      offset: [-3, 5, -1]
    holder:
      include: true
      alias: big-holder
      thickness: 2
  small-port:
    # This models an unknown variety of USB socket.
    include: true
    type: custom
    size: [6.5, 10, 13.6]
    alignment:
      side: NW
      segment: 2
    anchoring:
      anchor: back-plane
      offset: [6, 5, -1]
    holder:
      include: true
      alias: small-holder
      thickness: 2
