# A configuration fragment for Tom Short’s Dactyl-ManuForm, ca. v0.4.

# The long-term goal with this file is to have it produce Short’s design
# through the DMOTE application for upstream compatibility.
# As of DMOTE v0.6.0, the application is still missing the wire hook
# feature on the original Dactyl-ManuForm, and vertex-perfect imitation
# would be laborious.

keys:
  styles:
    default:  # Rough approximation of SA family.
      style: maquette
      switch-type: mx
      skirt-length: 5.75
      top-size: [12.7, 12.7, 6]
      unit-size: [1, 1]
    big:
      style: maquette
      switch-type: mx
      skirt-length: 5.75
      top-size: [12.7, 20, 6]
      unit-size: [1, 1.5]
key-clusters:
  main:
    position:
      anchor: origin
      # To match upstream STL more exactly, raise by the thickness of the
      # bottom plate. The Dactyl-ManuForm was not raised above the ground
      # plane to compensate for a bottom plate, but the DMOTE is.
      offset: [1, 0, 12.9]
    matrix-columns:
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 1
    aliases:
      m00: [0, first]
      m01: [1, first]
      m02: [2, first]
      m03: [3, first]
      mcu-base-key: [0, 0]
      back0: [0, last]
      back1: [1, last]
      back2: [2, last]
      right0: [last, 0]
  thumb0:
    position:
      anchor: m00
      offset: [-2, -28, -6]
    matrix-columns:
    - rows-above-home: 0
    - rows-above-home: 0
    aliases:
      thumb-tr: [1, 0]  # Top right.
      thumb-tl: [0, 0]
  thumb1:
    position:
      anchor: thumb-tl
      offset: [3.5, -26, -15]
    matrix-columns:
    - rows-above-home: 1
    - rows-above-home: 1
    aliases:
      thumb-mr: [1, 0]
      thumb-ml: [1, 1]
      thumb-br: [0, 0]
      thumb-bl: [0, 1]
by-key:
  parameters:
    layout:
      matrix:
        separation:
          column: 1.5
          row: 1.2
    wall:
      thickness: 2
      north:
        parallel: 5
        perpendicular: -15
      east:
        parallel: 5
        perpendicular: -15
      south:
        parallel: 5
        perpendicular: -15
      west:
        parallel: 5
        perpendicular: -15
  clusters:
    main:
      parameters:
        layout:
          matrix:
            neutral:
              column: 3
          pitch:
            base: 0
            progressive: 0.25
          roll:
            base: 0.26
            progressive: 0.09
      columns:
        first:
          parameters:
            wall:
              south:
                extent: 0
              west:
                parallel: 8
                perpendicular: -9
        "1":
          parameters:
            wall:
              south:
                extent: 0
        "2":
          parameters:
            layout:
              translation:
                mid: [0, 2.82, -4.5]
            wall:
              west:
                extent: 0
              south:
                extent: 0
        "4":
          parameters:
            layout:
              translation:
                late: [1, -12, 5.64]
    thumb0:
      parameters:
        key-style: big
        layout:
          pitch:
            base: 0.1745
          roll:
            base: -0.4014
          yaw:
            base: 0.1745
        wall:
          north:
            extent: 0
          east:
            extent: 0
          south:
            extent: 0
          west:
            extent: 0
      columns:
        first:
          parameters:
            layout:
              roll:
                intrinsic: 0
              yaw:
                intrinsic: 0
        last:
          parameters:
            layout:
              translation:
                late: [3, -4, -2.2]
    thumb1:
      parameters:
        layout:
          matrix:
            neutral:
              column: 1
            separation:
              column: 1
          pitch:
            base: -0.02
          roll:
            base: -0.59
          yaw:
            base: 0.94
        wall:
          east:
            extent: 0
      columns:
        first:
          parameters:
            # Because of the long walls of the case, full-extent walls cause
            # problems with OpenSCAD’s projections to the ground plane.
            # Therefore, walls on the first column are restricted.
            wall:
              north:
                extent: 4
              south:
                extent: 4
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.26
                  translation:
                    early: [0, -1, 1.7]
            last:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.05
                  translation:
                    early: [0, 1, 5.2]
        last:
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.1
                  yaw:
                    intrinsic: -0.06
                  translation:
                    early: [1.5, 0, 2.7]
            last:
              parameters:
                layout:
                  yaw:
                    intrinsic: -0.2
                  translation:
                    early: [0.6, 8, 4.5]
secondaries:
  back-plane:
    anchoring:
      anchor: back0
      side: NNE
      segment: 3
    override: [null, null, 3]
main-body:
  reflect: true
  key-mount-thickness: 4
  key-mount-corner-margin: 1.5
  web-thickness: 3.5
  bottom-plate:
    include: true
    installation:
      dome-caps: true
      thickness: 1.2
      inserts:
        include: true
        diameter:
          top: 5.1
          bottom: 5.31
        length: 3.8
      fasteners:
        bolt-properties:
          m-diameter: 3  # Speculation; Dactyl-ManuForm may have used non-metric.
          head-type: countersunk
          total-length: 6
          include-threading: false  # Threading not used with inserts.
        positions:
        - anchor: m00
          side: WSW
          offset: [-3, -7]
        - anchor: back0
          side: WSW
          offset: [0, 6]
        - anchor: back2
          side: NNE
          offset: [13.5, -3]
        - anchor: m02
          side: SSE
          offset: [-6, -4]
        - anchor: right0
          side: ESE
          offset: [-1, 10]
  tweaks:
    webbing:
      - chunk-size: 3
        hull-around:  # Between the two thumb clusters.
        - [thumb-tl, WNW, 0]
        - [thumb-ml, ENE, 0]
        - [thumb-tl, WSW, 0]
        - [thumb-ml, ESE, 0]
        - [thumb-tl, SSE, 0]
        - [thumb-mr, ENE, 0]
        - [thumb-tr, SSW, 0]
        - [thumb-mr, SSE, 0]
        - [thumb-tr, SSE, 0]
      - chunk-size: 3
        hull-around:  # Between thumb0 and the main cluster.
        - [thumb-tl, NNW, 0]
        - [m00, SSW, 0]
        - [thumb-tl, NNE, 0]
        - [m00, SSE, 0]
        - [thumb-tr, NNW, 0]
        - [m01, SSW, 0]
        - [thumb-tr, NNE, 0]
        - hull-around:
          - [m01, SSE, 0]
          - [m02, WNW, 0]
        - [thumb-tr, ENE, 0]
        - hull-around:
          - [m02, WNW, 0]
          - [m02, WSW, 0]
        - [thumb-tr, ESE, 0]
        - [m02, SSW, 0]
        - hull-around:
          - [m02, SSE, 0]
          - [m03, WSW, 0]
    to-floor:
      - at-ground: true
        hull-around:
        - [m00, WSW, 3, 4]
        - [thumb-ml, NNE, 3, 4]
      - at-ground: true
        hull-around:
        - [thumb-ml, NNW, 3, 4]
        - [thumb-bl, NNE, 3, 4]
      - at-ground: true
        hull-around:
        - [m03, SSW, 3, 4]
        - [thumb-tr, SSE, 3, 4]
      - at-ground: true
        hull-around:
        - [thumb-tr, SSE, 3, 4]
        - [thumb-mr, SSE, 3, 4]
      - at-ground: true
        hull-around:
        - [thumb-mr, SSW, 3, 4]
        - [thumb-br, SSE, 3, 4]
      - at-ground: true
        above-ground: false  # Extend the bottom plate only.
        hull-around:
        - [m03, SSW, 3]
        - [thumb-tr, SSE, 3]
        - [thumb-ml, NNE, 3]
        - [m00, WSW, 3]
      - at-ground: true
        above-ground: false  # Extend the bottom plate only.
        hull-around:
        - [thumb-mr, SSE, 3]
        - [thumb-ml, NNE, 3]
        - [thumb-tr, SSE, 3]
    thumb-to-finger-gap:
      - chunk-size: 3
        hull-around:
        - [m00, WSW, 0, 2]
        - [m00, WSW, 3, 4]
        - [thumb-tl, WNW, 0]
        - [thumb-ml, NNE, 0, 4]
      - chunk-size: 2
        hull-around:
        - [thumb-mr, SSE, 0, 4]
        - [thumb-tr, SSE, 0, 4]
        - [m03, SSW, 0, 4]
mcu:
  include: true
  type: promicro
  intrinsic-rotation: [0, 1.5708, 0]
  position:
    anchor: back-plane
    offset: [-17, -20, 11]
  support:
    shelf:
      include: true
      extra-space: [3, 19.9, 0.43]
      thickness: 3
      sides:
        lateral-thickness: 4
        overhang-thickness: 4
        overhang-width: 3
        offsets: [-34.9, 0]
ports:
  big-port:
    # This models an unknown variety of RJ9 socket.
    include: true
    type: custom
    size: [10.78, 9, 18.38]
    alignment:
      side: NE
      segment: 2
    position:
      anchor: back-plane
      offset: [-8, 5, 0]
    holder:
      include: true
      thickness: 2
  small-port:
    # This models an unknown variety of USB socket.
    include: true
    type: custom
    size: [6.5, 10, 13.6]
    alignment:
      side: NW
      segment: 2
    position:
      anchor: back-plane
      offset: [10, 5, 0]
    holder:
      include: true
      thickness: 2
